"""initial schema

Revision ID: b16989f61b2d
Revises: 
Create Date: 2026-04-02 18:58:26.781077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16989f61b2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('student', 'admin', name='roleenum'), nullable=False),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quiz_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('initiated_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='jobstatusenum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('extracted_questions', sa.JSON(), nullable=True),
    sa.Column('questions_imported', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syllabus_uploads',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('upload_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='jobstatusenum'), nullable=True),
    sa.Column('extracted_structure', sa.JSON(), nullable=True),
    sa.Column('subjects_imported', sa.Integer(), nullable=True),
    sa.Column('topics_imported', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subtopics', sa.JSON(), nullable=True),
    sa.Column('nlp_keyword_tags', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('difficulty_weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subtopic', sa.String(length=255), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('question_image_urls', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=5), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficultyenum'), nullable=False),
    sa.Column('source_type', sa.Enum('PYQ', 'practice', 'scraped', name='sourcetypeenum'), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('nlp_keyword_tags', sa.JSON(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('scrape_job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['scrape_jobs.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('repetition_count', sa.Integer(), nullable=True),
    sa.Column('last_score_pct', sa.Float(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_revision_schedules_user_id_topic_id', 'revision_schedules', ['user_id', 'topic_id'], unique=False)
    op.create_table('topic_masteries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('topic_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('weakness_score', sa.Float(), nullable=True),
    sa.Column('mastery_level', sa.Enum('Weak', 'Moderate', 'Strong', name='masterylevelenum'), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('correct_attempts', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_s', sa.Float(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('next_revision_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_topic_masteries_user_topic')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_masteries')
    op.drop_index('ix_revision_schedules_user_id_topic_id', table_name='revision_schedules')
    op.drop_table('revision_schedules')
    op.drop_table('questions')
    op.drop_table('topics')
    op.drop_table('syllabus_uploads')
    op.drop_table('scrape_jobs')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subjects')
    # ### end Alembic commands ###
